---
title: "Decompose"
author: "Julia Bruneau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(zoo)
library(IHA)
library(PearsonDS)
library(ggplot2)
library(dplyr)
library(lubridate)
library(readr)
library(knitr)
```


```{r}
setwd("/Users/VT_SA/Documents/HARP")
pwater <- read_csv("forA51800_pwater.csv")
pwater$date <- as.Date(pwater$index, format = "%m/%d/%Y %H:%M")
pwater$week <- week(pwater$date)
pwater$month <- month(pwater$date)
pwater$year <- year(pwater$date)
```


```{r}
#dailyAGWS <- aggregate(pwater$AGWS, by = list(pwater$date), FUN = "mean")
#colnames(dailyAGWS) <- c("date", "AGWS")
#monthlyAGWS <- aggregate(pwater$AGWS, by = list(pwater$month, pwater$year), FUN = "mean")
#colnames(monthlyAGWS) <- c("month","year", "AGWS")
#yearlyAGWS <- aggregate(pwater$AGWS, by = list(pwater$year), FUN = "mean")
#colnames(yearlyAGWS) <- c("year", "AGWS")
```


```{r}
# the functions below require data that is created with ts()
AGWS_ts <- ts(pwater$AGWS, start = c(1984,1), end = c(2020,12), frequency = 12)
# frequency = 12 (monthly); = 4 (quarterly); = 1 (annual)
head(AGWS_ts)
```

## Multiplicative

```{r}
agws_decompM <- decompose(AGWS_ts, type = "multiplicative") #here we note the type of data set we are working with

plot(agws_decompM)

decomp_dfM <- data.frame(agws_decompM$figure)
colnames(decomp_dfM) <- c('Seasonality')
rownames(decomp_dfM) <- c('Jan','Feb','Mar','Apr','May','June','July','Aug','Sep','Oct','Nov','Dec')
decomp_dfM


plot(agws_decompM$figure, type = 'l', ylab = 'AGWS Fitted Trend (in)', xaxt = 'n', xlab = NA, col = 'blue')
axis(1, at = seq(1,12,1), labels = c('Jan','Feb','Mar','Apr','May','June','July','Aug','Sep','Oct','Nov','Dec'))
title(main = 'Active Groundwater Storage Fitted Trend (1984-2020)')

plot(agws_decompM$trend, type = 'l', ylab = 'AGWS Fitted Trend (in)', xlab = NA, col = 'blue')
title(main = 'Active Groundwater Storage Fitted Trend')
```


## Additive

```{r}
agws_decompA <- decompose(AGWS_ts, type = "additive") #here we note the type of data set we are working with

plot(agws_decompA)

decomp_dfA <- data.frame(agws_decompA$figure)
colnames(decomp_dfA) <- c('Seasonality')
rownames(decomp_dfA) <- c('Jan','Feb','Mar','Apr','May','June','July','Aug','Sep','Oct','Nov','Dec')
decomp_dfA

plot(agws_decompA$figure, type = 'l', ylab = 'AGWS Fitted Trend (in)', xaxt = 'n', xlab = NA, col = 'blue')
axis(1, at = seq(1,12,1), labels = c('Jan','Feb','Mar','Apr','May','June','July','Aug','Sep','Oct','Nov','Dec'))
title(main = 'Active Groundwater Storage Fitted Trend (1984-2020)')

plot(agws_decompA$trend, type = 'l', ylab = 'AGWS Fitted Trend (in)', xlab = NA, col = 'blue')
title(main = 'Active Groundwater Storage Fitted Trend')
```


## Justification

```{r}
#multiplicative
acfM <- acf(agws_decompM$random, na.action = na.omit)

ljung_boxM <- Box.test(agws_decompM$random, lag=1, type="Ljung-Box")
print(ljung_boxM)

#additive
acfA <- acf(agws_decompA$random, na.action = na.omit)

ljung_boxA <- Box.test(agws_decompA$random, lag=1, type="Ljung-Box")
print(ljung_boxA)
```
