---
title: "mapping_oldCode"
author: "Glenn Campagna"
date: "2023-07-11"
output: html_document
---
## Temporary storage of extra code from mapping_codeReview.R


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r (Old) Filter Facils/Sources by map_type Extent, warning=FALSE, eval = FALSE, echo= FALSE}
## If chunk @ line ~ 400 isn't working, use this 
## filtering MPs or facilities by extent we want, 
facils_all <- facils$all #create temporary df for use in sqldf for ordering

if (map_type == "basin") { #'type' variable will either be: basin, locality, or region 
  for(i in rivseg){. #newly moved into this loop
    if(i==rivseg[1]){
    segs$basin <- fn_extract_basin(segs$all, i)
    }
    if(i!=rivseg[1]){
    segs$basin <- rbind(segs$basin, fn_extract_basin(segs$all, i))
    }
  }
  facils$all <- facils$all[!is.na(facils$all$Longitude),] #remove rows with missing coords for sf creation
  facils$all <- facils$all[!is.na(facils$all$Latitude),]
  facils$sf <- st_as_sf(facils$all, coords = c("Longitude","Latitude"))
  st_crs(facils$sf) <- 4326 
  segs_basin <- segs$basin
  segs$basin_sp <- process_geom(segs$basin, "geom")
  segs$basin_sf <- st_as_sf(segs$basin_sp)
  st_crs(segs$basin_sf) <- 4326 
  if (metric_type == "modeled") {
    facils$basin <- sqldf("SELECT facils_all.* 
                          FROM facils_all 
                          WHERE riverseg 
                          IN (select segs_basin.riverseg from segs_basin) 
                          AND riverseg IS NOT NULL") # previously: facils$basin <- subset(facils$all, riverseg %in% segs$basin$riverseg & riverseg!="NULL")
    facils$basin <- st_filter(facils$sf, segs$basin_sf)
    coords <- st_coordinates(facils$basin$geometry)
    colnames(coords) <- c("Longitude", "Latitude")
    facils$basin <- st_drop_geometry(facils$basin)
    
  } else if (metric_type == "measured") {
    facils$basin <- st_filter(facils$sf, segs$basin_sf)
    coords <- st_coordinates(facils$basin$geometry)
    colnames(coords) <- c("Longitude", "Latitude")
    facils$basin <- st_drop_geometry(facils$basin)
  }
  facils$basin <- with(facils, sqldf("SELECT * 
                                     FROM basin 
                                     WHERE hydrocode not like 'wsp_%'") )  # Filter out WSP (optional)
  facils_basin <- facils$basin #create temporary df for use in sqldf for ordering
  facils_basin <- sqldf(paste0( #ordering the data using sqldf 
  "SELECT facils_basin.*  
   FROM facils_basin 
   ORDER BY", ' ', df$runlabel[1], ' ', "DESC")) #ordering by the metric of interest, descending 
  facils$basin <- facils_basin 
  rm(facils_basin) #removing the ordered data frame since we're finished with it 
  facils$basin$NUM <- seq(1, nrow(facils$basin))
  facils$basin <- cbind(facils$basin, coords)
  facils$within <- facils$basin #generic name for facils within extent to be used by mapping fun 
#  sf_use_s2(FALSE) # switch off Spherical geometry
#  bbox <- st_buffer(st_as_sfc(st_bbox(segs$basin_sf)), .05) #slightly past basin
}
if (map_type == "locality") {
  ## pull locality and geometry out of data frame with the locality parameter given
  locality_sf <- counties$sf[counties$sf$name == locality, ] #if REST IS working
  locality_sp <- process_geom(as.data.frame(locality_sf), "dh_geofield") #for reverse-fill process for map 
  facils$all <- facils$all[!is.na(facils$all$Longitude),] #remove rows with missing coords for sf creation
  facils$all <- facils$all[!is.na(facils$all$Latitude),]
  facils$sf <- st_as_sf(facils$all, coords = c("Longitude","Latitude"))
  
  st_crs(facils$sf) <- 4326 
  st_crs(locality_sf) <- 4326 
  facils$within <- st_filter(facils$sf, locality_sf) #filter MPs by the extent of the locality
  segs_all <- segs$all[-which(segs$all$geom == ""), ] #need to remove rows with empty geometries 
  segs$sp <- process_geom(segs_all, "geom") #takes a few seconds
  rm(segs_all)
  segs$sf <- st_as_sf(segs$sp)
  st_crs(segs$sf) <- 4326
  sf_use_s2(FALSE)
  segs$basin <- st_filter(segs$sf, locality_sf) #filter basins by locality
  segs$basin <- st_drop_geometry(segs$basin)
  coords <- st_coordinates(facils$within$geometry)
  colnames(coords) <- c("Longitude","Latitude")
  facils_within <- st_drop_geometry(facils$within) #create temporary df for use in sqldf for ordering
  facils_within <- sqldf(paste0( #ordering the data using sqldf 
  "SELECT facils_within.*  
   FROM facils_within 
   ORDER BY", ' ', df$runlabel[1], ' ', "DESC") #ordering by the metric of interest, descending 
  )
  facils$within <- facils_within 
  rm(facils_within) #removing the ordered data frame since we're finished with it 
  facils$within$NUM <- seq(1, nrow(facils$within))
  facils$within <- cbind(facils$within, coords)
  facils$within<- st_as_sf(facils$within, coords = c("Longitude","Latitude"))
  facils$within <- cbind(facils$within, coords)
  st_crs(facils$within) <- 4326
  facils$within <- st_drop_geometry(facils$within)
#  sf_use_s2(FALSE) # switch off Spherical geometry
#  bbox <- st_buffer(st_as_sfc(st_bbox(locality_sf)), .05) #slightly past basin
}
if (map_type == "region") {
  #region geometries stored in region_geom_list under the region name 
  #pull region of interest given in params from list of region geometries 
  region_list <- region_geom_list[names(region_geom_list) == region]
  region_sf <- st_sfc(region_list) #create sf object from the region specified
  region_sfd <- st_as_sf(region_sf) #for region_sp
  segs$region_sf <- region_sfd # for darker outline around region
  st_crs(segs$region_sf) <- 4326
  region_sp <- as_Spatial(region_sfd, cast = FALSE)
  st_crs(region_sf) <- 4326 #set coordinate system for spatial filtering 
  segs_all <- segs$all[-which(segs$all$geom == ""), ] #need to remove rows with empty geometries 
  segs$sp <- process_geom(segs_all, "geom") #takes a few seconds
  rm(segs_all)
  segs$sf <- st_as_sf(segs$sp)
  st_crs(segs$sf) <- 4326
  sf_use_s2(FALSE)
  segs$basin <- st_filter(segs$sf, region_sf) #filter basins by the region
  segs$basin <- st_drop_geometry(segs$basin)
  ## filtering by region:
  facils$all <- facils$all[!is.na(facils$all$Longitude),] #remove rows with missing coords for sf creation
  facils$all <- facils$all[!is.na(facils$all$Latitude),]
  facils$sf <- st_as_sf(facils$all, coords = c("Longitude","Latitude"))
  st_crs(facils$sf) <- 4326 
  facils$within <- st_filter(facils$sf, region_sf) #filter to MPs within the region
  coords <- st_coordinates(facils$within$geometry)
  colnames(coords) <- c("Longitude","Latitude")
  facils_within <- st_drop_geometry(facils$within) #create temporary df for use in sqldf for ordering
  facils_within <- sqldf(paste0( #ordering the data using sqldf 
  "SELECT facils_within.*  
   FROM facils_within 
   ORDER BY", ' ', df$runlabel[1], ' ', "DESC") #ordering by the metric of interest, descending 
  )
  facils$within <- facils_within 
  rm(facils_within) #removing the ordered data frame since we're finished with it 
  facils$within$NUM <- seq(1, nrow(facils$within))
  facils$within <- cbind(facils$within, coords)
  facils$within<- st_as_sf(facils$within, coords = c("Longitude","Latitude"))
  facils$within <- cbind(facils$within, coords)
  facils$within <- st_drop_geometry(facils$within)
#  st_crs(facils$within) <- 4326
#  facils_region <- st_filter(facils_sf, region_sf) ## needs to be modified for regions w 2 or more polygons
#  coords <- st_coordinates(facils_region$geometry)
#  colnames(coords) <- c("Longitude","Latitude")
#  facils_region <- cbind(facils_region, coords)
#  facils_region <- st_drop_geometry(facils_region)
#  facils_region <- sqldf(paste0( #ordering the data using sqldf 
#  "SELECT facils_region.*  
#   FROM facils_region 
#   ORDER BY", ' ', df$runlabel[1], ' ', "DESC") #ordering by the metric of interest, descending 
#   )
#  facils_region$NUM <- seq(1, nrow(facils_region))
#  facils_within <- facils_region #facils$within needs to stay as MPs for table generation
#  sf_use_s2(FALSE) # switch off Spherical geometry
#  bbox <- st_buffer(st_as_sfc(st_bbox(region_sf)), .05) #slightly past basin
}
facils$within <- facils$within[,colSums(is.na(facils$within))<nrow(facils$within)] #remove columns with all NAs
rm(facils_all)
```

```{r, eval = FALSE, echo= FALSE}
## No longer used, but keeping for now:

#- - - - add 5 yr avg use (MGY) with wd current- PER FACILITY - - -
# for (i in 1:nrow(facils$basin)){
# val <- RomProperty$new(ds,list(
#     featureid= facils$basin$featureid[i],
#     propname= "wd_current_mgy"), 
#   TRUE)
# five_mgy <- val$propvalue
# table$five_mgy[i] <- round(five_mgy,2)
# }
#- - -  5 year avg PER SOURCE - - - 
#what 5 years should we be using 
#why are the numbers sometimes very different
#for (i in 1:nrow(facils$basin)){
#  fiveavg <- mean(na.omit(facils$basin$'2022'[i],facils$basin$'2021'[i],facils$basin$'2020'[i],facils$basin$'2019'[i],facils$basin$'2018'[i], na.rm= TRUE))
#  table$five_mgy_new[i] <- round(fiveavg, 2)
#}
#table$five_mgy_new <- facils$basin$fiveyr_avg_mgy_2

# #- - - -add upstream or downstream - - - removed for now, not priority
# 
# #needs to be adjusted 
# for(i in 1:nrow(facils$basin)){ 
#   if(facils$basin$riverseg[i] == rivseg)
#   {
#     up_down<- "Upstream"
#     table$Upstream_Downstream[i] <- up_down
#   }
#   else if (facils$basin$riverseg[i] != rivseg)
#   {
#     up_down <- "Downstream"
#     table$Upstream_Downstream[i] <- up_down
#   }
# }

# Full join facility model data & facility foundation data
#    facils$all <- with(facils, sqldf("select foundatn.* , mdat.* from foundatn 
#      left outer join mdat
#      on (foundatn.Facility_hydroid = mdat.featureid)
#      UNION
#      select foundatn.* , mdat.* from mdat
#      left outer join foundatn
#      on (foundatn.Facility_hydroid = mdat.featureid)
#      ") ) #facils$all <- merge(x=facils$mdat, y=facils$foundatn, by.x="featureid", by.y="Facility_hydroid", all=TRUE)

#Won't be necessary once new facilities geom csv is integrated
#if (!"Locality" %in% colnames(facils$all)) {
#  propname <- facils$all$propname
#  facils$all <- process_geom(facils$all, "dh_geofield")
#  facils$all <- st_as_sf(facils$all)
#  st_crs(facils$all) <- 4326
#  facil_join <- st_join(facils$all, counties$sf)
#  facils$all <- cbind(propname, facils$all, facil_join$name)
#  names(facils$all)[names(facils$all) == 'facil_join.name'] <- 'Locality'
#  facils$all <- st_drop_geometry(facils$all)

#  facil_fulljoin <- sqldf("SELECT * FROM facil_featr as a
#                      LEFT OUTER JOIN facils_foundatn as b
#                      ON (a.featureid = b.Facility_hydroid)
#                      UNION
#                      SELECT * FROM facils_foundatn as a
#                      LEFT OUTER JOIN facil_featr as b
#                      ON (a.Facility_hydroid = b.featureid)" 
#                      ) #not successful 
#}


## Table generation as of 7/13/23
if (type=="source"){
  #source-unique columns for table
  
  table$Source_Type = facils$within$Source_Type
  table$Source = facils$within$MP_Name
  #No permitted capacity added to source-level table
  
  table <- table[, c("Number", "Facility", "Source", 
                        "Source_Type", "Locality", "rivsegName", 
                        "Rivseg", "fiveYrAvg_mgy")] #order source-level table
  
} else if (type=="facility"){
    names(facils$within)[names(facils$within) == 'featureid'] <- 'Facility_hydroid'
    for (i in 1:nrow(facils$within)){
      systemObj <- RomProperty$new(ds,list(
        featureid = facils$within$Facility_hydroid[i],
        propcode= "vahydro-1.0"), 
      TRUE)
        if (is.na(systemObj$pid) == TRUE) { #if no feature exists 
        table$vwp_max_mgy[i] <- "No Permit"
      } else {
      permCapac <- RomProperty$new(ds,list(
        featureid = systemObj$pid,
        propname = 'vwp_max_mgy'),
      TRUE)
      table$vwp_max_mgy[i] <- permCapac$propcode
      }
    } 
    table$vwp_max_mgy <-  replace(table$vwp_max_mgy, table$vwp_max_mgy==0, "No Permit") #Replace zeros with "no permit"
    
    if (metric !="fiveyr_avg_mgy") {
      #get metric columns into table
      table[,df$runlabel[1]] <- round(facils$within[,df$runlabel[1]], digits = 2)
      table[,df$runlabel[2]] <- round(facils$within[,df$runlabel[2]], digits = 2)
      
      # rename runid metrics with metric1 and metric2
      colnames(table)[grepl('runid_11',colnames(table))] <- 'metric2020'
      colnames(table)[grepl('runid_13',colnames(table))] <- 'metric2040'
      
      table <- table[, c("Number", "Facility", 
                        "Locality", "rivsegName", 
                        "Rivseg", "vwp_max_mgy", 
                        "metric2020", "metric2040")] #order table w/ model metrics
      
    } else {
      table <- table[, c("Number", "Facility", 
                        "Locality", "rivsegName", 
                        "Rivseg", "vwp_max_mgy", 
                        "fiveYrAvg_mgy")] #order table w/out model metrics
    }
  }
```