---
title: "metricVisualization"
author: "Glenn Campagna"
date: '2023-05-26'
output: html_document
---

#Visualizing the L90 metric 

#L90 represents the lowest consecutive 90 day average daily streamflow over the simulation period -- a prolonged drought 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dataRetrieval)
library(lubridate)
library(data.table)
library(IHA)
library(zoo)
```


```{r}
#Bringing in USGS flow data for analysis and plotting 
siteno <- '01668000' #guage for Rappahannock river @ Fredericksburg VA
startDate <- '1990-01-01'
endDate <- '2023-12-31'
pCode <- '00060' #the code for discharge in cfs
sCode <- '00003' #the code for daily mean data
flow <- readNWISdv(siteno, pCode, startDate, endDate, sCode) #creates a data frame with flow data from the specified gauge 
colnames(flow) <- c('Agency', 'Site No', 'Date', 'Flow', 'Code') #rename the columns for table
```


```{r}
#Manipulating data 
flow$Date <- as.Date(flow$Date, format= "%m/%d/%Y")
flow$month <-month(flow$Date)
flow$year <- year(flow$Date)
```

```{r}
flow_mon <- aggregate(flow$Flow, by = list(flow$month, flow$year), FUN = 'mean') #Flow averaged monthly, for plotting
```

```{r}
flowz <- zoo(flow$Flow, order.by = flow$Date) #create zoo object for use in IHA function
Qout_g2 <- group2(flowz, year = 'water')#IHA group2() finds L30, L90, etc.
```

```{r}
l90 <- data.frame(Qout_g2$`90 Day Min`)
ndx = which.min(as.numeric(l90[,1]))
l90_Qout = round(Qout_g2[ndx,]$`90 Day Min`,6) #This var represents the main L90 metric across the entire period of analysis
l90_year = Qout_g2[ndx,]$year #Gives the year which the L90 occured 
```

```{r}
#Can we use IHA group1() to identify the lowest-flow months within the L90 year?
Qout_g1 <- data.frame(group1(flowz, year = 'water'))
g1_l90yr <- subset(Qout_g1, subset = rownames(Qout_g1) == l90_year)
```




