---
title: "mapping_locality"
author: "Glenn Campagna"
date: "2023-06-13"
output: html_document
params:
  locality: ["Culpeper"]
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(hydrotools)
library(sp)
library(rgeos)
library(sf)
library(nhdplusTools)
library(ggmap)
library(ggplot2)
library(ggnewscale)   
library(ggsn)
library(ggspatial)
library(ggrepel)
library(nhdplusTools)
library(dplyr)
library(flextable)
library(geosphere)

basepath='/var/www/R'
source('/var/www/R/config.R')
ds <- RomDataSource$new("http://deq1.bse.vt.edu/d.dh", rest_uname)
ds$get_token(rest_pw)
site <- 'http://deq1.bse.vt.edu/d.dh'
```

```{r UserInputs, echo=FALSE}
locality <- params$locality
map_name <- paste0(locality, '_map')
```

```{r Establish Functions, echo=FALSE}
# Convert any data frame w/ geometry stored as "character" to "SpatialXxxDataFrame" (Xx_sp)
process_geom <- function(features) {
  for (i in 1:nrow(features)) {
    sp.i <- sp::addAttrToGeom(
      x=readWKT(features[i,]$dh_geofield), 
      y=as.data.frame(as.list(subset(features[i,],select=-c(dh_geofield)))),
      match.ID=TRUE
    )
    if (i == 1) {
      # start with one 
      features_sp <- sp.i
    } else {
      # append
      features_sp <- rbind(features_sp, sp.i)
    }
  }
  return(features_sp)
}
```

```{r}
# Get County fips
fips_filename <- paste("vahydro_usafips_export.csv",sep="")
fips_destfile <- paste(tempdir(),fips_filename,sep="\\")
download.file(paste(site,"usafips_geom_export",sep="//"), destfile = fips_destfile, method = "libcurl")
fips.csv <- read.csv(file=paste(tempdir() , fips_filename,sep="\\"), header=TRUE, sep=",")
fips.csv$dh_geofield <- fips.csv$fips_geom 
fips_sp <- process_geom(fips.csv)
fips.csv$dh_geofield <- fips.csv$fips_centroid
fips_centroid_sp <- process_geom(fips.csv)
```

```{r}
## Selecting only the locality of interest 
locality_df <- fips.csv[fips.csv$fips_name == locality, ]
locality_df <- subset(locality_df, select = -c(dh_geofield))
locality_df$dh_geofield <- locality_df$fips_geom
locality_sp <- process_geom(locality_df)
locality_sf <- st_as_sf(locality_sp, crs = 4326)
```

```{r}
#Create boundary box based around locality with a buffer 
ggmap_bbox <- st_buffer(st_as_sfc(st_bbox(locality_sf)), .03)
ggmap_bbox <- setNames(st_bbox(ggmap_bbox), c("left", "bottom", "right", "top"))
```

```{r}
#Generating basemap
basemap <- ggmap::get_stamenmap(maptype = "terrain", color="color", bbox = ggmap_bbox, zoom = 12)
basemap <- ggmap(basemap)
```

```{r}
map <- basemap + #ggplot2::
    geom_sf(data = locality_sf, inherit.aes = FALSE, color = "black", fill = NA, lwd=2) +
    # County Labels
    geom_text(data = locality_df, 
               aes(fips_longitude, fips_latitude, label = fips_name, fontface="bold.italic", family="serif"), 
               colour = "#003333", size=12, show.legend=FALSE) +
  # Original scalebar
   # ggsn::scalebar(data = locality_sf, location = 'bottomleft', dist = 5, dist_unit = 'mi',  # dist variable scaled based on size of boundary box 
    #               transform = TRUE, model = 'WGS84',st.bottom=FALSE, st.size= 3, st.dist = 0.03) +
    # north arrow
    ggspatial::annotation_north_arrow(which_north = "grid", location = "tr",
                                      height = unit(4, "cm"),width = unit(3, "cm"), 
                                      style = north_arrow_orienteering(text_size = 35)
                                      ) 
  #### Adjustable Scale Bar Using Joey's anchoring method 
#    ggsn::scalebar(data = bbox_sf, location = 'bottomleft', dist = dist, dist_unit = 'mi', 
#                                transform = TRUE, model = 'WGS84',st.bottom=FALSE, 
#                                st.size = 9,
#                                anchor = c(
#                                  x = (((extent$x[2] - extent$x[1])/3)+extent$x[1])-0.45,
#                                  y = extent$y[1]+(extent$y[1])*0.001
#                                ))
```

```{r Save Map.png, echo=FALSE}
ggsave(
  filename = paste(export_path, map_name, ".png", sep=""),
  plot = map,
  width = 25,
  height = 20
  )
```
